### PR TITLE
Fix support for coordination numbers

### PR DESCRIPTION
**Pull request by EricIO**
This commit fixes the calculation of the control number for
coordination numbers. Previously the calculation was done on the
parsed number where the date part of the number had been normalized to
the actual date (i.e sans the added 60 to it.) The test coordination
numbers provided by skatteverket has a control number that is correct
if you do the calculation with the added 60.

### CODE REVIEW

**Comment by bombsimon** [comment]
Thanks for the PR, nice find!

I think it feels a bit weird to move the `IsCoordination` to `Parsed` because that is something that's specific to personal identity numbers and not regular luhn numbers or organisation numbers.

What do you think about keeping it on the `Person` struct but instead of normalising the day we just keep it as is from the input and create a getter for the actual day without coordination number? I guess that if you want to use the actual _date_ for a person you would opt for the `Date` field either way, right? 

I'm thinking something like this, WDYT?

```diff
diff --git a/private_person.go b/private_person.go
index eda16c2..1fa165b 100644
--- a/private_person.go
+++ b/private_person.go
@@ -52,6 +52,12 @@ type Person struct {
 	Zodiac         Zodiac
 }
 
+// GetDay will return the day as a valid date day, meaning it's the parsed
+// personal identity number but witout a potential coordination number.
+func (p *Person) GetDay() int {
+	return p.Day % minCoordinationNumber
+}
+
 // NewPerson parses and returns a pointer to a Person based on the input. If the
 // input cannot be parsed an error will be returned. Upon creating a Person the
 // century, date and county will be set.
@@ -74,7 +80,6 @@ func NewPersonFromParsed(parsed *Parsed) (*Person, error) {
 	}
 
 	if person.Day > minCoordinationNumber {
-		person.Day %= 60
 		person.IsCoordination = true
 	}
 
@@ -127,7 +132,7 @@ func (p *Person) String() string {
 
 	return fmt.Sprintf(
 		"%02d%02d%02d%s%03d%d",
-		p.Year, p.Month, p.Day,
+		p.Year, p.Month, p.GetDay(),
 		p.Divider, p.Serial, cd,
 	)
 }
@@ -154,7 +159,7 @@ func (p *Person) SetCentury() error {
 		"2006-01-02",
 		fmt.Sprintf(
 			"%02d%02d-%02d-%02d",
-			time.Now().Year()/100, p.Year, p.Month, p.Day,
+			time.Now().Year()/100, p.Year, p.Month, p.GetDay(),
 		),
 	)
 
@@ -195,7 +200,7 @@ func (p *Person) SetDate() error {
 			"%d-%02d-%02d",
 			p.Century+p.Year,
 			p.Month,
-			p.Day,
+			p.GetDay(),
 		),
 	)
```

This change makes your change to the test still pass but keeps the coordination field on `Person`. If you think this sounds OK I can push this or you can do it in your PR and I'll merge and draft a new release.

**Comment by EricIO** [comment]
Feel free to push, I wont have the time until I get back to the office this afternoon :) Looks good.

**Comment by bombsimon** [comment]
Ugh, I tried to keep your commit but for some reason it got dropped when I created a merge commit. I don't know if it's because your commit in the PR isn't related to your GitHub account but it was not my intention. Sorry about that, appreciate the contribution!

Released a v1.0.0 with this change (and a rename of the package so watch out for that!)

**Comment by EricIO** [comment]
No worries :) and thanks for the quick response!

**Pull request merged**
